#!/usr/bin/env sh
set -euo pipefail

export GIT_SUBMODULE_CMD="git submodule --quiet"
export UPDATE_CMD="${GIT_SUBMODULE_CMD} update --init"

usage() {
  cat <<EOF
usage: git submodule-url-rewrite [-h|--help] [-v|--verbose] [-q|--quiet] [-r|--recursive] [-s|--no-stage] [-u|--no-update] sed-script

Rewrites all submodule urls using the given sed-script

options:
  -h|--help       Print this help
  -v|--verbose    Make this script verbose
  -q|--quiet      Don't print anything
  -r|--recursive  Also rewrite submodules of submodules
  -s|--no-stage   Don't stage changed .gitmodule files for commit
  -u|--no-update  Don't run '${UPDATE_CMD}' in each submodule

sed-script: A sed script used to transform urls.
EOF
}

export VERBOSE=false
export QUIET=false
export RECURSIVE=""
export NO_STAGE=false
export NO_UPDATE=false
export SED_COMMAND=""

while true; do
  case "${1:-""}" in

    -h|--help)
      usage && exit 0
    ;;

    "")
      usage
      exit 1
    ;;

    -v|--verbose)
      VERBOSE=true && shift
      GIT_SUBMODULE_CMD="git submodule"
      UPDATE_CMD="${GIT_SUBMODULE_CMD} update --init"
    ;;

    -q|--quiet)
      QUIET=true && shift
    ;;

    -r|--recursive)
      RECURSIVE="--recursive" && shift
    ;;

    -s|--no-stage)
      NO_STAGE=true && shift
    ;;

    -u|--no-update)
      NO_UPDATE=true && shift
    ;;

    *)
      SED_COMMAND="${1}" && shift
      break
    ;;

  esac
done

sm_url_rewrite(){
  set -euo pipefail
  if [ "${VERBOSE}" = true ]; then set -x; fi

  local gitmodules="${toplevel}/.gitmodules"
  local old_url="$(git config --file="${gitmodules}" "submodule.${name}.url")"
  local new_url="$(echo "${old_url}" | sed -r -e "${SED_COMMAND}")"

  if [ "${QUIET}" = false ]; then
    echo "${name}: '${old_url}' -> '${new_url}'"
  fi

  git config --file="${gitmodules}" "submodule.${name}.url" "${new_url}"
  ${GIT_SUBMODULE_CMD} sync

  if [ "${NO_STAGE}" = false ]; then
    git -C "${toplevel}" add "${gitmodules}"
  fi

  if [ "${NO_UPDATE}" = false ]; then
    ${UPDATE_CMD}
  fi
}
export -f sm_url_rewrite

if [ "${VERBOSE}" = true ]; then set -x; fi

if [ "${NO_UPDATE}" = false ]; then
  ${UPDATE_CMD}
fi

${GIT_SUBMODULE_CMD} foreach ${RECURSIVE} sm_url_rewrite
